export default [
  {
    adult: false,
    backdrop_path: "/rOmUuQEZfPXglwFs5ELLLUDKodL.jpg",
    genre_ids: [35, 28, 14],
    id: 845781,
    original_language: "en",
    original_title: "Red One",
    overview:
      "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous bounty hunter in a globe-trotting, action-packed mission to save Christmas.",
    popularity: 1008.073,
    poster_path: "/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg",
    release_date: "2024-11-10",
    title: "Red One",
    video: false,
    vote_average: 7.2,
    vote_count: 33,
  },
  {
    adult: false,
    backdrop_path: "/8mjYwWT50GkRrrRdyHzJorfEfcl.jpg",
    genre_ids: [28, 12],
    id: 558449,
    original_language: "en",
    original_title: "Gladiator II",
    overview:
      "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people. Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
    popularity: 379.021,
    poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    release_date: "2024-11-22",
    title: "Gladiator II",
    video: false,
    vote_average: 8.4,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
    genre_ids: [16, 14, 12],
    id: 823219,
    original_language: "lv",
    original_title: "Straume",
    overview:
      "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
    popularity: 355.505,
    poster_path: "/dzDMewC0Hwv01SROiWgKOi4iOc1.jpg",
    release_date: "2024-11-22",
    title: "Flow",
    video: false,
    vote_average: 8.598,
    vote_count: 178,
  },
  {
    adult: false,
    backdrop_path: "/tElnmtQ6yz1PjN1kePNl8yMSb59.jpg",
    genre_ids: [16, 12, 10751, 35],
    id: 1241982,
    original_language: "en",
    original_title: "Moana 2",
    overview:
      "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
    popularity: 283.31,
    poster_path: "/yh64qw9mgXBvlaWDi7Q9tpUBAvH.jpg",
    release_date: "2024-11-27",
    title: "Moana 2",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/ljNVBysYnPCwLqP3HXL7T1thZxu.jpg",
    genre_ids: [18, 14, 10749],
    id: 402431,
    original_language: "en",
    original_title: "Wicked",
    overview:
      "Elphaba, an ostracized but defiant girl born with green skin, and Glinda, a privileged aristocrat born popular, become extremely unlikely friends in the magical Land of Oz. As the two girls struggle with their opposing personalities, their friendship is tested as both begin to fulfill their destinies as Glinda the Good and The Wicked Witch of the West.",
    popularity: 264.234,
    poster_path: "/c5Tqxeo1UpBvnAc3csUm7j3hlQl.jpg",
    release_date: "2024-11-22",
    title: "Wicked",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/rdfd1kzdPmGVEfMiqyZxrn50kYq.jpg",
    genre_ids: [18, 10749],
    id: 1059128,
    original_language: "en",
    original_title: "Queer",
    overview:
      "In 1950s Mexico City, William Lee, an American expat in his late forties, leads a solitary life amidst a small American community. However, the arrival in town of Eugene Allerton, a young student, stirs William into finally establishing a meaningful connection with someone.",
    popularity: 61.533,
    poster_path: "/6yVAgbEBMgdTjigPlgVLfo0F4j6.jpg",
    release_date: "2024-11-27",
    title: "Queer",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/wbDkvShcrveXNFsgyujY4kdurVa.jpg",
    genre_ids: [35, 10749],
    id: 957119,
    original_language: "en",
    original_title: "Sidelined: The QB & Me",
    overview:
      "Dallas, a burdened but headstrong dancer, is determined to get into the best dance school in the country—her late mother’s alma mater. However, that dream is suddenly derailed when the cheeky yet secretly grieving football star, Drayton, crashes into her life with a unique story of his own. Will the two of them be able to grow into their dreams together, or will their dreams be sidelined?",
    popularity: 38.981,
    poster_path: "/kWSfmkKs3i62k5iFzmdut0xudGk.jpg",
    release_date: "2024-11-15",
    title: "Sidelined: The QB & Me",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/ky3mP0ehmZfH6YsboBJa9l0STyC.jpg",
    genre_ids: [99],
    id: 1214537,
    original_language: "en",
    original_title: "Never Look Away",
    overview:
      "CNN camerawoman Margaret Moth fearlessly captures footage of war zones. After receiving catastrophic injuries in the crosshairs of battle, she returns to work with more courage than ever. An intimate portrait of a trailblazing female photojournalist. Features interviews with Moth’s family and friends, including CNN’s Christiane Amanpour. A Sundance film festival premiere directed by Lucy Lawless.",
    popularity: 29.478,
    poster_path: "/s4zKcr9zcm3sPIPyyOpC7zxGJIC.jpg",
    release_date: "2024-11-22",
    title: "Never Look Away",
    video: false,
    vote_average: 6.7,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: "/rz2AruNH8sdOaAuYrVLDfTMqXCm.jpg",
    genre_ids: [10749, 18],
    id: 1292359,
    original_language: "tl",
    original_title: "Hello, Love, Again",
    overview:
      "Five years on from when Joy said goodbye to Ethan and Hong Kong to pursue her dreams in Canada. After fighting for their love to conquer the time, distance and a global shutdown that kept them apart, Joy and Ethan meet again in Canada but realize that they have also changed a lot, individually.",
    popularity: 29.372,
    poster_path: "/7R940b9RNNKLDrAI1GmCjOd5ta.jpg",
    release_date: "2024-11-15",
    title: "Hello, Love, Again",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/thDLoKyWdgK6EWXwGsjYqAFenuN.jpg",
    genre_ids: [28, 80, 53],
    id: 1182387,
    original_language: "en",
    original_title: "Armor",
    overview:
      "Armored truck security guard James Brody is working with his son Casey transporting millions of dollars between banks when a team of thieves led by Rook orchestrate a takeover of their truck to seize the riches. Following a violent car chase, Rook soon has the armored truck surrounded and James and Casey find themselves cornered onto a decrepit bridge.",
    popularity: 28.762,
    poster_path: "/6wtKfSdx9RTeWGfT2zsYUHM7vDf.jpg",
    release_date: "2024-11-22",
    title: "Armor",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/iewaNwseOf44yoBrQI8uEU1OJy0.jpg",
    genre_ids: [18, 53],
    id: 1278263,
    original_language: "fa",
    original_title: "دانه‌ی انجیر معابد",
    overview:
      "An investigating judge in the Revolutionary Court in Tehran grapples with mistrust and paranoia as nationwide political protests intensify and his gun mysteriously disappears. Suspecting the involvement of his wife and their two daughters, he imposes drastic measures at home, causing tensions to rise. Step by step, social norms and the rules of family life are being suspended.",
    popularity: 22.443,
    poster_path: "/d6chGhHP6vzo2VJPivLvZuwnq7j.jpg",
    release_date: "2024-11-27",
    title: "The Seed of the Sacred Fig",
    video: false,
    vote_average: 7.7,
    vote_count: 71,
  },
  {
    adult: false,
    backdrop_path: "/oZMpjEvO19ILidHNmRn1QTkXgpQ.jpg",
    genre_ids: [16, 14, 35, 18, 10751],
    id: 1030588,
    original_language: "ja",
    original_title: "化け猫あんずちゃん",
    overview:
      'Precocious tween Karin finds herself abandoned by her father in rural Japan. Living in a temple with her grandfather, she meets Anzu, a giant "ghost cat" and notorious layabout tasked with looking after her. Distrustful of her new guardian, Karin sabotages Anzu\'s odd jobs for the townsfolk and befriends the eccentric local forest spirits. In an effort to win Karin over, Anzu accidentally makes a deal with the devil, and all Hell breaks loose.',
    popularity: 21.855,
    poster_path: "/g7QIJabY49KNP9osUAWH3xMsqSI.jpg",
    release_date: "2024-11-15",
    title: "Ghost Cat Anzu",
    video: false,
    vote_average: 7.5,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: "/aHoJmalP8J0k13YPC1ew4kAuR2g.jpg",
    genre_ids: [18, 36, 10752],
    id: 1079244,
    original_language: "en",
    original_title: "Bonhoeffer: Pastor. Spy. Assassin.",
    overview:
      "As the world teeters on the brink of annihilation, Dietrich Bonhoeffer is swept into the epicenter of a deadly plot to assassinate Hitler. With his faith and fate at stake, Bonhoeffer must choose between upholding his moral convictions or risking it all to save millions of Jews from genocide. Will his shift from preaching peace to plotting murder alter the course of history or cost him everything?",
    popularity: 20.756,
    poster_path: "/mLqwKGSVrxXP5iMqgikEia6WB07.jpg",
    release_date: "2024-11-22",
    title: "Bonhoeffer: Pastor. Spy. Assassin.",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/zHfJ3DYCpNP0bgAnXuxCJFZwoih.jpg",
    genre_ids: [18, 53],
    id: 1211472,
    original_language: "de",
    original_title: "September 5",
    overview:
      "During the 1972 Munich Olympics, an American broadcasting team is thrust from covering sports to reporting a dramatic hostage situation involving Israeli athletes. A young producer, unexpectedly leading the live broadcast, faces difficult decisions as time runs out, rumors spread, and the hostages' lives hang in the balance.",
    popularity: 20.209,
    poster_path: "/cI5WWXPGy3wwQ1IsWqxAURXxAGh.jpg",
    release_date: "2024-11-29",
    title: "September 5",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/xIrTIAS7UAFBv8NeGHpoEEvuEGy.jpg",
    genre_ids: [18, 10402],
    id: 1038263,
    original_language: "en",
    original_title: "Maria",
    overview:
      "1977: Maria Callas, once the world's greatest opera diva, lives in seclusion in Paris with her staff and her two poodles. Her health is getting worse and worse. Then she receives a request to go on tour again. Will La Callas sing again? And if so, for whom?",
    popularity: 19.822,
    poster_path: "/3oQRG0bwPUqE4N4n8z2kAzr7e40.jpg",
    release_date: "2024-11-27",
    title: "Maria",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18, 10751, 10749],
    id: 1205925,
    original_language: "en",
    original_title: "Saint Nick of Bethlehem",
    overview:
      "Distraught over losing his son, Nick finds closure and discovers a new purpose when he takes on the role of Santa Claus.",
    popularity: 15.982,
    poster_path: "/joRJmlyvWPj7Uv2zWfelWHrKzf6.jpg",
    release_date: "2024-11-14",
    title: "Saint Nick of Bethlehem",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [27],
    id: 1198717,
    original_language: "en",
    original_title: "Wicked Witch",
    overview:
      "Countess Elizabeth Bathory lures a young woman to her lair so that she can give birth to the title creature.",
    popularity: 15.866,
    poster_path: "/rVcd7F5HISKGVHZju2xzQLdEjWT.jpg",
    release_date: "2024-11-23",
    title: "Wicked Witch",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/3KbNuZiWkhMWyeHguse8Sjjy6Zo.jpg",
    genre_ids: [35, 18],
    id: 1229261,
    original_language: "en",
    original_title: "The Black Sea",
    overview:
      "Khalid, a charismatic big dreamer from Brooklyn, with no follow-thru gets stuck in a small town on the Black Sea after chasing an opportunity for money that goes wrong. Being the only black guy in the town, he quickly becomes the center of the town’s attention. His New York City street bop is all he has to survive. In his pursuit to get home he finds connection in a way he never expected with a local woman. Together they make their small dreams big.",
    popularity: 12.597,
    poster_path: "/h4y6dZkfvYnrZBhdWmwbKWqDg7D.jpg",
    release_date: "2024-11-22",
    title: "The Black Sea",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/m5G2iMzzxDygPHkzNRAV20DggsZ.jpg",
    genre_ids: [18, 10749, 35],
    id: 1274047,
    original_language: "en",
    original_title: "Albany Road",
    overview:
      "On her way to the most important meeting of her career, severe weather forces a New York executive to share a rental car with her former nemesis, her ex-fiancé's mother, only to discover that the mother is hiding a major secret.",
    popularity: 12.251,
    poster_path: "/3kPiE2X1neiHDcAXEzCKK3fQJD6.jpg",
    release_date: "2024-11-15",
    title: "Albany Road",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [53],
    id: 1218631,
    original_language: "en",
    original_title: "Scream Before You Die",
    overview:
      "A woman is kidnapped, tortured and left for dead. The killers think they got away with it. They have no idea who or what is coming for them.",
    popularity: 11.648,
    poster_path: "/mt8FqaswAMvMP5xOxSTLQPKEAL3.jpg",
    release_date: "2024-12-01",
    title: "Scream Before You Die",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/8mjYwWT50GkRrrRdyHzJorfEfcl.jpg",
    genre_ids: [28, 12],
    id: 558449,
    original_language: "en",
    original_title: "Gladiator II",
    overview:
      "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
    popularity: 379.021,
    poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    release_date: "2024-11-22",
    title: "Gladiator II",
    video: false,
    vote_average: 8.4,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
    genre_ids: [16, 14, 12],
    id: 823219,
    original_language: "lv",
    original_title: "Straume",
    overview:
      "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
    popularity: 355.505,
    poster_path: "/dzDMewC0Hwv01SROiWgKOi4iOc1.jpg",
    release_date: "2024-11-22",
    title: "Flow",
    video: false,
    vote_average: 8.598,
    vote_count: 178,
  },
  {
    adult: false,
    backdrop_path: "/tElnmtQ6yz1PjN1kePNl8yMSb59.jpg",
    genre_ids: [16, 12, 10751, 35],
    id: 1241982,
    original_language: "en",
    original_title: "Moana 2",
    overview:
      "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
    popularity: 283.31,
    poster_path: "/yh64qw9mgXBvlaWDi7Q9tpUBAvH.jpg",
    release_date: "2024-11-27",
    title: "Moana 2",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/ljNVBysYnPCwLqP3HXL7T1thZxu.jpg",
    genre_ids: [18, 14, 10749],
    id: 402431,
    original_language: "en",
    original_title: "Wicked",
    overview:
      "Elphaba, an ostracized but defiant girl born with green skin, and Glinda, a privileged aristocrat born popular, become extremely unlikely friends in the magical Land of Oz. As the two girls struggle with their opposing personalities, their friendship is tested as both begin to fulfill their destinies as Glinda the Good and The Wicked Witch of the West.",
    popularity: 264.234,
    poster_path: "/c5Tqxeo1UpBvnAc3csUm7j3hlQl.jpg",
    release_date: "2024-11-22",
    title: "Wicked",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/rdfd1kzdPmGVEfMiqyZxrn50kYq.jpg",
    genre_ids: [18, 10749],
    id: 1059128,
    original_language: "en",
    original_title: "Queer",
    overview:
      "In 1950s Mexico City, William Lee, an American expat in his late forties, leads a solitary life amidst a small American community. However, the arrival in town of Eugene Allerton, a young student, stirs William into finally establishing a meaningful connection with someone.",
    popularity: 61.533,
    poster_path: "/6yVAgbEBMgdTjigPlgVLfo0F4j6.jpg",
    release_date: "2024-11-27",
    title: "Queer",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/wbDkvShcrveXNFsgyujY4kdurVa.jpg",
    genre_ids: [35, 10749],
    id: 957119,
    original_language: "en",
    original_title: "Sidelined: The QB & Me",
    overview:
      "Dallas, a burdened but headstrong dancer, is determined to get into the best dance school in the country—her late mother’s alma mater. However, that dream is suddenly derailed when the cheeky yet secretly grieving football star, Drayton, crashes into her life with a unique story of his own. Will the two of them be able to grow into their dreams together, or will their dreams be sidelined?",
    popularity: 38.981,
    poster_path: "/kWSfmkKs3i62k5iFzmdut0xudGk.jpg",
    release_date: "2024-11-15",
    title: "Sidelined: The QB & Me",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/ky3mP0ehmZfH6YsboBJa9l0STyC.jpg",
    genre_ids: [99],
    id: 1214537,
    original_language: "en",
    original_title: "Never Look Away",
    overview:
      "CNN camerawoman Margaret Moth fearlessly captures footage of war zones. After receiving catastrophic injuries in the crosshairs of battle, she returns to work with more courage than ever. An intimate portrait of a trailblazing female photojournalist. Features interviews with Moth’s family and friends, including CNN’s Christiane Amanpour. A Sundance film festival premiere directed by Lucy Lawless.",
    popularity: 29.478,
    poster_path: "/s4zKcr9zcm3sPIPyyOpC7zxGJIC.jpg",
    release_date: "2024-11-22",
    title: "Never Look Away",
    video: false,
    vote_average: 6.7,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: "/rz2AruNH8sdOaAuYrVLDfTMqXCm.jpg",
    genre_ids: [10749, 18],
    id: 1292359,
    original_language: "tl",
    original_title: "Hello, Love, Again",
    overview:
      "Five years on from when Joy said goodbye to Ethan and Hong Kong to pursue her dreams in Canada. After fighting for their love to conquer the time, distance and a global shutdown that kept them apart, Joy and Ethan meet again in Canada but realize that they have also changed a lot, individually.",
    popularity: 29.372,
    poster_path: "/7R940b9RNNKLDrAI1GmCjOd5ta.jpg",
    release_date: "2024-11-15",
    title: "Hello, Love, Again",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/thDLoKyWdgK6EWXwGsjYqAFenuN.jpg",
    genre_ids: [28, 80, 53],
    id: 1182387,
    original_language: "en",
    original_title: "Armor",
    overview:
      "Armored truck security guard James Brody is working with his son Casey transporting millions of dollars between banks when a team of thieves led by Rook orchestrate a takeover of their truck to seize the riches. Following a violent car chase, Rook soon has the armored truck surrounded and James and Casey find themselves cornered onto a decrepit bridge.",
    popularity: 28.762,
    poster_path: "/6wtKfSdx9RTeWGfT2zsYUHM7vDf.jpg",
    release_date: "2024-11-22",
    title: "Armor",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/iewaNwseOf44yoBrQI8uEU1OJy0.jpg",
    genre_ids: [18, 53],
    id: 1278263,
    original_language: "fa",
    original_title: "دانه‌ی انجیر معابد",
    overview:
      "An investigating judge in the Revolutionary Court in Tehran grapples with mistrust and paranoia as nationwide political protests intensify and his gun mysteriously disappears. Suspecting the involvement of his wife and their two daughters, he imposes drastic measures at home, causing tensions to rise. Step by step, social norms and the rules of family life are being suspended.",
    popularity: 22.443,
    poster_path: "/d6chGhHP6vzo2VJPivLvZuwnq7j.jpg",
    release_date: "2024-11-27",
    title: "The Seed of the Sacred Fig",
    video: false,
    vote_average: 7.7,
    vote_count: 71,
  },
  {
    adult: false,
    backdrop_path: "/oZMpjEvO19ILidHNmRn1QTkXgpQ.jpg",
    genre_ids: [16, 14, 35, 18, 10751],
    id: 1030588,
    original_language: "ja",
    original_title: "化け猫あんずちゃん",
    overview:
      'Precocious tween Karin finds herself abandoned by her father in rural Japan. Living in a temple with her grandfather, she meets Anzu, a giant "ghost cat" and notorious layabout tasked with looking after her. Distrustful of her new guardian, Karin sabotages Anzu\'s odd jobs for the townsfolk and befriends the eccentric local forest spirits. In an effort to win Karin over, Anzu accidentally makes a deal with the devil, and all Hell breaks loose.',
    popularity: 21.855,
    poster_path: "/g7QIJabY49KNP9osUAWH3xMsqSI.jpg",
    release_date: "2024-11-15",
    title: "Ghost Cat Anzu",
    video: false,
    vote_average: 7.5,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: "/aHoJmalP8J0k13YPC1ew4kAuR2g.jpg",
    genre_ids: [18, 36, 10752],
    id: 1079244,
    original_language: "en",
    original_title: "Bonhoeffer: Pastor. Spy. Assassin.",
    overview:
      "As the world teeters on the brink of annihilation, Dietrich Bonhoeffer is swept into the epicenter of a deadly plot to assassinate Hitler. With his faith and fate at stake, Bonhoeffer must choose between upholding his moral convictions or risking it all to save millions of Jews from genocide. Will his shift from preaching peace to plotting murder alter the course of history or cost him everything?",
    popularity: 20.756,
    poster_path: "/mLqwKGSVrxXP5iMqgikEia6WB07.jpg",
    release_date: "2024-11-22",
    title: "Bonhoeffer: Pastor. Spy. Assassin.",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/zHfJ3DYCpNP0bgAnXuxCJFZwoih.jpg",
    genre_ids: [18, 53],
    id: 1211472,
    original_language: "de",
    original_title: "September 5",
    overview:
      "During the 1972 Munich Olympics, an American broadcasting team is thrust from covering sports to reporting a dramatic hostage situation involving Israeli athletes. A young producer, unexpectedly leading the live broadcast, faces difficult decisions as time runs out, rumors spread, and the hostages' lives hang in the balance.",
    popularity: 20.209,
    poster_path: "/cI5WWXPGy3wwQ1IsWqxAURXxAGh.jpg",
    release_date: "2024-11-29",
    title: "September 5",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/xIrTIAS7UAFBv8NeGHpoEEvuEGy.jpg",
    genre_ids: [18, 10402],
    id: 1038263,
    original_language: "en",
    original_title: "Maria",
    overview:
      "1977: Maria Callas, once the world's greatest opera diva, lives in seclusion in Paris with her staff and her two poodles. Her health is getting worse and worse. Then she receives a request to go on tour again. Will La Callas sing again? And if so, for whom?",
    popularity: 19.822,
    poster_path: "/3oQRG0bwPUqE4N4n8z2kAzr7e40.jpg",
    release_date: "2024-11-27",
    title: "Maria",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18, 10751, 10749],
    id: 1205925,
    original_language: "en",
    original_title: "Saint Nick of Bethlehem",
    overview:
      "Distraught over losing his son, Nick finds closure and discovers a new purpose when he takes on the role of Santa Claus.",
    popularity: 15.982,
    poster_path: "/joRJmlyvWPj7Uv2zWfelWHrKzf6.jpg",
    release_date: "2024-11-14",
    title: "Saint Nick of Bethlehem",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [27],
    id: 1198717,
    original_language: "en",
    original_title: "Wicked Witch",
    overview:
      "Countess Elizabeth Bathory lures a young woman to her lair so that she can give birth to the title creature.",
    popularity: 15.866,
    poster_path: "/rVcd7F5HISKGVHZju2xzQLdEjWT.jpg",
    release_date: "2024-11-23",
    title: "Wicked Witch",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/3KbNuZiWkhMWyeHguse8Sjjy6Zo.jpg",
    genre_ids: [35, 18],
    id: 1229261,
    original_language: "en",
    original_title: "The Black Sea",
    overview:
      "Khalid, a charismatic big dreamer from Brooklyn, with no follow-thru gets stuck in a small town on the Black Sea after chasing an opportunity for money that goes wrong. Being the only black guy in the town, he quickly becomes the center of the town’s attention. His New York City street bop is all he has to survive. In his pursuit to get home he finds connection in a way he never expected with a local woman. Together they make their small dreams big.",
    popularity: 12.597,
    poster_path: "/h4y6dZkfvYnrZBhdWmwbKWqDg7D.jpg",
    release_date: "2024-11-22",
    title: "The Black Sea",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/m5G2iMzzxDygPHkzNRAV20DggsZ.jpg",
    genre_ids: [18, 10749, 35],
    id: 1274047,
    original_language: "en",
    original_title: "Albany Road",
    overview:
      "On her way to the most important meeting of her career, severe weather forces a New York executive to share a rental car with her former nemesis, her ex-fiancé's mother, only to discover that the mother is hiding a major secret.",
    popularity: 12.251,
    poster_path: "/3kPiE2X1neiHDcAXEzCKK3fQJD6.jpg",
    release_date: "2024-11-15",
    title: "Albany Road",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [53],
    id: 1218631,
    original_language: "en",
    original_title: "Scream Before You Die",
    overview:
      "A woman is kidnapped, tortured and left for dead. The killers think they got away with it. They have no idea who or what is coming for them.",
    popularity: 11.648,
    poster_path: "/mt8FqaswAMvMP5xOxSTLQPKEAL3.jpg",
    release_date: "2024-12-01",
    title: "Scream Before You Die",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
];
